export type CountryData = {
  name: string;
  code: string;
  min: number;
  max: number;
};

// Comprehensive list of countries with their dial codes and typical mobile number lengths
export const COUNTRY_CODES: CountryData[] = [
  { name: "Afghanistan", code: "+93", min: 9, max: 9 },
  { name: "Albania", code: "+355", min: 8, max: 9 },
  { name: "Algeria", code: "+213", min: 9, max: 9 },
  { name: "Andorra", code: "+376", min: 6, max: 6 },
  { name: "Angola", code: "+244", min: 9, max: 9 },
  { name: "Antigua and Barbuda", code: "+1", min: 10, max: 10 },
  { name: "Argentina", code: "+54", min: 10, max: 10 },
  { name: "Armenia", code: "+374", min: 8, max: 8 },
  { name: "Australia", code: "+61", min: 9, max: 9 },
  { name: "Austria", code: "+43", min: 10, max: 11 },
  { name: "Azerbaijan", code: "+994", min: 9, max: 9 },
  { name: "Bahamas", code: "+1", min: 10, max: 10 },
  { name: "Bahrain", code: "+973", min: 8, max: 8 },
  { name: "Bangladesh", code: "+880", min: 10, max: 10 },
  { name: "Barbados", code: "+1", min: 10, max: 10 },
  { name: "Belarus", code: "+375", min: 9, max: 9 },
  { name: "Belgium", code: "+32", min: 9, max: 9 },
  { name: "Belize", code: "+501", min: 7, max: 7 },
  { name: "Benin", code: "+229", min: 8, max: 8 },
  { name: "Bhutan", code: "+975", min: 8, max: 8 },
  { name: "Bolivia", code: "+591", min: 8, max: 8 },
  { name: "Bosnia and Herzegovina", code: "+387", min: 8, max: 8 },
  { name: "Botswana", code: "+267", min: 8, max: 8 },
  { name: "Brazil", code: "+55", min: 10, max: 11 },
  { name: "Brunei", code: "+673", min: 7, max: 7 },
  { name: "Bulgaria", code: "+359", min: 8, max: 9 },
  { name: "Burkina Faso", code: "+226", min: 8, max: 8 },
  { name: "Burundi", code: "+257", min: 8, max: 8 },
  { name: "Cambodia", code: "+855", min: 8, max: 9 },
  { name: "Cameroon", code: "+237", min: 9, max: 9 },
  { name: "Canada", code: "+1", min: 10, max: 10 },
  { name: "Cape Verde", code: "+238", min: 7, max: 7 },
  { name: "Central African Republic", code: "+236", min: 8, max: 8 },
  { name: "Chad", code: "+235", min: 8, max: 8 },
  { name: "Chile", code: "+56", min: 9, max: 9 },
  { name: "China", code: "+86", min: 11, max: 11 },
  { name: "Colombia", code: "+57", min: 10, max: 10 },
  { name: "Comoros", code: "+269", min: 7, max: 7 },
  { name: "Congo (DRC)", code: "+243", min: 9, max: 9 },
  { name: "Congo (Republic)", code: "+242", min: 9, max: 9 },
  { name: "Costa Rica", code: "+506", min: 8, max: 8 },
  { name: "Croatia", code: "+385", min: 9, max: 9 },
  { name: "Cuba", code: "+53", min: 8, max: 8 },
  { name: "Cyprus", code: "+357", min: 8, max: 8 },
  { name: "Czech Republic", code: "+420", min: 9, max: 9 },
  { name: "Denmark", code: "+45", min: 8, max: 8 },
  { name: "Djibouti", code: "+253", min: 8, max: 8 },
  { name: "Dominica", code: "+1", min: 10, max: 10 },
  { name: "Dominican Republic", code: "+1", min: 10, max: 10 },
  { name: "Ecuador", code: "+593", min: 9, max: 9 },
  { name: "Egypt", code: "+20", min: 10, max: 10 },
  { name: "El Salvador", code: "+503", min: 8, max: 8 },
  { name: "Equatorial Guinea", code: "+240", min: 9, max: 9 },
  { name: "Eritrea", code: "+291", min: 7, max: 7 },
  { name: "Estonia", code: "+372", min: 7, max: 8 },
  { name: "Eswatini", code: "+268", min: 8, max: 8 },
  { name: "Ethiopia", code: "+251", min: 9, max: 9 },
  { name: "Fiji", code: "+679", min: 7, max: 7 },
  { name: "Finland", code: "+358", min: 9, max: 10 },
  { name: "France", code: "+33", min: 9, max: 9 },
  { name: "Gabon", code: "+241", min: 7, max: 8 },
  { name: "Gambia", code: "+220", min: 7, max: 7 },
  { name: "Georgia", code: "+995", min: 9, max: 9 },
  { name: "Germany", code: "+49", min: 10, max: 11 },
  { name: "Ghana", code: "+233", min: 9, max: 9 },
  { name: "Greece", code: "+30", min: 10, max: 10 },
  { name: "Grenada", code: "+1", min: 10, max: 10 },
  { name: "Guatemala", code: "+502", min: 8, max: 8 },
  { name: "Guinea", code: "+224", min: 9, max: 9 },
  { name: "Guinea-Bissau", code: "+245", min: 9, max: 9 },
  { name: "Guyana", code: "+592", min: 7, max: 7 },
  { name: "Haiti", code: "+509", min: 8, max: 8 },
  { name: "Honduras", code: "+504", min: 8, max: 8 },
  { name: "Hungary", code: "+36", min: 9, max: 9 },
  { name: "Iceland", code: "+354", min: 7, max: 7 },
  { name: "India", code: "+91", min: 10, max: 10 },
  { name: "Indonesia", code: "+62", min: 9, max: 12 },
  { name: "Iran", code: "+98", min: 10, max: 10 },
  { name: "Iraq", code: "+964", min: 10, max: 10 },
  { name: "Ireland", code: "+353", min: 9, max: 9 },
  { name: "Israel", code: "+972", min: 9, max: 9 },
  { name: "Italy", code: "+39", min: 9, max: 10 },
  { name: "Jamaica", code: "+1", min: 10, max: 10 },
  { name: "Japan", code: "+81", min: 10, max: 10 },
  { name: "Jordan", code: "+962", min: 9, max: 9 },
  { name: "Kazakhstan", code: "+7", min: 10, max: 10 },
  { name: "Kenya", code: "+254", min: 9, max: 9 },
  { name: "Kiribati", code: "+686", min: 8, max: 8 },
  { name: "Kuwait", code: "+965", min: 8, max: 8 },
  { name: "Kyrgyzstan", code: "+996", min: 9, max: 9 },
  { name: "Laos", code: "+856", min: 10, max: 10 },
  { name: "Latvia", code: "+371", min: 8, max: 8 },
  { name: "Lebanon", code: "+961", min: 7, max: 8 },
  { name: "Lesotho", code: "+266", min: 8, max: 8 },
  { name: "Liberia", code: "+231", min: 8, max: 8 },
  { name: "Libya", code: "+218", min: 9, max: 9 },
  { name: "Liechtenstein", code: "+423", min: 7, max: 9 },
  { name: "Lithuania", code: "+370", min: 8, max: 8 },
  { name: "Luxembourg", code: "+352", min: 9, max: 9 },
  { name: "Madagascar", code: "+261", min: 9, max: 9 },
  { name: "Malawi", code: "+265", min: 9, max: 9 },
  { name: "Malaysia", code: "+60", min: 9, max: 10 },
  { name: "Maldives", code: "+960", min: 7, max: 7 },
  { name: "Mali", code: "+223", min: 8, max: 8 },
  { name: "Malta", code: "+356", min: 8, max: 8 },
  { name: "Marshall Islands", code: "+692", min: 7, max: 7 },
  { name: "Mauritania", code: "+222", min: 8, max: 8 },
  { name: "Mauritius", code: "+230", min: 8, max: 8 },
  { name: "Mexico", code: "+52", min: 10, max: 10 },
  { name: "Micronesia", code: "+691", min: 7, max: 7 },
  { name: "Moldova", code: "+373", min: 8, max: 8 },
  { name: "Monaco", code: "+377", min: 8, max: 9 },
  { name: "Mongolia", code: "+976", min: 8, max: 8 },
  { name: "Montenegro", code: "+382", min: 8, max: 8 },
  { name: "Morocco", code: "+212", min: 9, max: 9 },
  { name: "Mozambique", code: "+258", min: 9, max: 9 },
  { name: "Myanmar", code: "+95", min: 9, max: 10 },
  { name: "Namibia", code: "+264", min: 9, max: 9 },
  { name: "Nauru", code: "+674", min: 7, max: 7 },
  { name: "Nepal", code: "+977", min: 10, max: 10 },
  { name: "Netherlands", code: "+31", min: 9, max: 9 },
  { name: "New Zealand", code: "+64", min: 8, max: 10 },
  { name: "Nicaragua", code: "+505", min: 8, max: 8 },
  { name: "Niger", code: "+227", min: 8, max: 8 },
  { name: "Nigeria", code: "+234", min: 10, max: 10 },
  { name: "North Korea", code: "+850", min: 10, max: 10 },
  { name: "North Macedonia", code: "+389", min: 8, max: 8 },
  { name: "Norway", code: "+47", min: 8, max: 8 },
  { name: "Oman", code: "+968", min: 8, max: 8 },
  { name: "Pakistan", code: "+92", min: 10, max: 10 },
  { name: "Palau", code: "+680", min: 7, max: 7 },
  { name: "Palestine", code: "+970", min: 9, max: 9 },
  { name: "Panama", code: "+507", min: 8, max: 8 },
  { name: "Papua New Guinea", code: "+675", min: 8, max: 8 },
  { name: "Paraguay", code: "+595", min: 9, max: 9 },
  { name: "Peru", code: "+51", min: 9, max: 9 },
  { name: "Philippines", code: "+63", min: 10, max: 10 },
  { name: "Poland", code: "+48", min: 9, max: 9 },
  { name: "Portugal", code: "+351", min: 9, max: 9 },
  { name: "Qatar", code: "+974", min: 8, max: 8 },
  { name: "Romania", code: "+40", min: 9, max: 9 },
  { name: "Russia", code: "+7", min: 10, max: 10 },
  { name: "Rwanda", code: "+250", min: 9, max: 9 },
  { name: "Saint Kitts and Nevis", code: "+1", min: 10, max: 10 },
  { name: "Saint Lucia", code: "+1", min: 10, max: 10 },
  { name: "Saint Vincent and the Grenadines", code: "+1", min: 10, max: 10 },
  { name: "Samoa", code: "+685", min: 7, max: 7 },
  { name: "San Marino", code: "+378", min: 10, max: 10 },
  { name: "Sao Tome and Principe", code: "+239", min: 7, max: 7 },
  { name: "Saudi Arabia", code: "+966", min: 9, max: 9 },
  { name: "Senegal", code: "+221", min: 9, max: 9 },
  { name: "Serbia", code: "+381", min: 8, max: 9 },
  { name: "Seychelles", code: "+248", min: 7, max: 7 },
  { name: "Sierra Leone", code: "+232", min: 8, max: 8 },
  { name: "Singapore", code: "+65", min: 8, max: 8 },
  { name: "Slovakia", code: "+421", min: 9, max: 9 },
  { name: "Slovenia", code: "+386", min: 8, max: 8 },
  { name: "Solomon Islands", code: "+677", min: 7, max: 7 },
  { name: "Somalia", code: "+252", min: 8, max: 8 },
  { name: "South Africa", code: "+27", min: 9, max: 9 },
  { name: "South Korea", code: "+82", min: 9, max: 10 },
  { name: "South Sudan", code: "+211", min: 9, max: 9 },
  { name: "Spain", code: "+34", min: 9, max: 9 },
  { name: "Sri Lanka", code: "+94", min: 9, max: 9 },
  { name: "Sudan", code: "+249", min: 9, max: 9 },
  { name: "Suriname", code: "+597", min: 7, max: 7 },
  { name: "Sweden", code: "+46", min: 9, max: 9 },
  { name: "Switzerland", code: "+41", min: 9, max: 9 },
  { name: "Syria", code: "+963", min: 9, max: 9 },
  { name: "Taiwan", code: "+886", min: 9, max: 9 },
  { name: "Tajikistan", code: "+992", min: 9, max: 9 },
  { name: "Tanzania", code: "+255", min: 9, max: 9 },
  { name: "Thailand", code: "+66", min: 9, max: 9 },
  { name: "Timor-Leste", code: "+670", min: 8, max: 8 },
  { name: "Togo", code: "+228", min: 8, max: 8 },
  { name: "Tonga", code: "+676", min: 7, max: 7 },
  { name: "Trinidad and Tobago", code: "+1", min: 10, max: 10 },
  { name: "Tunisia", code: "+216", min: 8, max: 8 },
  { name: "Turkey", code: "+90", min: 10, max: 10 },
  { name: "Turkmenistan", code: "+993", min: 8, max: 8 },
  { name: "Tuvalu", code: "+688", min: 7, max: 7 },
  { name: "Uganda", code: "+256", min: 9, max: 9 },
  { name: "Ukraine", code: "+380", min: 9, max: 9 },
  { name: "United Arab Emirates", code: "+971", min: 9, max: 9 },
  { name: "United Kingdom", code: "+44", min: 10, max: 10 },
  { name: "United States", code: "+1", min: 10, max: 10 },
  { name: "Uruguay", code: "+598", min: 8, max: 8 },
  { name: "Uzbekistan", code: "+998", min: 9, max: 9 },
  { name: "Vanuatu", code: "+678", min: 7, max: 7 },
  { name: "Vatican City", code: "+379", min: 10, max: 10 },
  { name: "Venezuela", code: "+58", min: 10, max: 10 },
  { name: "Vietnam", code: "+84", min: 9, max: 9 },
  { name: "Yemen", code: "+967", min: 9, max: 9 },
  { name: "Zambia", code: "+260", min: 9, max: 9 },
  { name: "Zimbabwe", code: "+263", min: 9, max: 9 }
];
